Repository Mecha-Karen/acord, pull requests merged in 2022-01, with the labels that each got.

#15 master
  examples/guess.py
Labels: enhancement

#18 Update main.py
  acord/webhooks/main.py
Labels: enhancement

#24 Guild Scheduled Event
  acord/bases/__init__.py
  acord/bases/enums/events.py
  acord/models/__init__.py
  acord/models/guild.py
  acord/models/guild_sched_event.py
  acord/payloads.py
Labels: enhancement, todo

#27 Couple word spelling changes
  docs/source/events.rst
Labels: documentation
